# generate samples for test set for trained models if there aren't enough samples generated by the model
# usage: python generate.py
# if there are errors, consider running update_previous_outputs.py first to make sure results have uniform format

import pandas as pd
from iota.utils import PACKAGE_DIR, get_git_hash
from iota.eval_utils import add_run_alias_to_df, get_run_alias, update_df_columns
from iota.iota_trainer import IotaTrainer, IotaArguments
from pathlib import Path
import yaml
import json
from datetime import datetime
from loguru import logger

# number of samples to generate for the test set
TARGET_SAMPLES = 5

out_dir = PACKAGE_DIR / "out"

# load all results
results_fn = out_dir / "all_results.jsonl"
df = pd.read_json(results_fn, lines=True)

logger.info(f"Starting length: {len(df)}")

# find subdirs in out_dir
subdirs = [x for x in out_dir.iterdir() if x.is_dir()]

# recursively find all leaf dirs
leaf_dirs = []
while subdirs:
    subdir = subdirs.pop()
    subsubdirs = [x for x in subdir.iterdir() if x.is_dir()]
    if not subsubdirs:
        leaf_dirs.append(subdir)
    else:
        subdirs.extend(subsubdirs)

logger.info(len(leaf_dirs))

# remove directories without model.json if "iota" is part of the directory
for leaf_dir in leaf_dirs:
    if "iota" in str(leaf_dir):
        if not (leaf_dir / "model.json").exists():
            logger.info(f"removing {leaf_dir} because no model.json was found")
            # remove dir, including its contents
            for f in leaf_dir.iterdir():
                f.unlink()
            leaf_dir.rmdir()
            continue 

    # get results and check if they are already in df
    results_fn = leaf_dir / "results.json"
    # if results file does not exist, remove the directory
    if not results_fn.exists() and input(f"Remove {leaf_dir}? (y/n): ") == "y":
        for f in leaf_dir.iterdir():
            f.unlink()
        leaf_dir.rmdir()
        continue

    # if results file is there, check if it is in the df
    with open(results_fn, "r") as f:
        results = json.load(f)

    # date string from leaf_dir 
    date_str = leaf_dir.name
    # verify that date_str is in the correct format
    try:
        datetime.strptime(date_str, "%Y-%m-%d_%H-%M-%S")
    except ValueError:
        logger.error(f"Invalid date string: {date_str}, check dir: {leaf_dir}")
        continue

    # get config and run_alias
    config_fn = leaf_dir / "config.yaml"
    with open(config_fn, "r") as f:
        config = yaml.safe_load(f)
    run_alias = get_run_alias(config)

    if "test" not in results:
        logger.warning(f"Results file does not contain 'test' key: {results_fn}, skipping")
        continue 

    git_hash = results["test"][0]["git_hash"]

    all_test_results = [] 
    for test_results in results["test"]:
        all_test_results.extend(test_results["results"])
    for generated_sample in all_test_results: 
        generated_sample.update(config)
        generated_sample["date"] = date_str
        generated_sample["git_hash"] = git_hash
        generated_sample["run_alias"] = run_alias

    # add to df if not already there
    new_df = pd.DataFrame(all_test_results)
    new_df = update_df_columns(new_df)

    df = pd.concat([df, new_df], ignore_index=True)
    # remove duplicates when everything is the same
    df = df.drop_duplicates()


# keep only 5 samples for each task for each author for each benchmark on each run alias 
# if there are not enough samples, generate more
group_dfs = df.groupby(["run_alias", "benchmark", "author_id", "task"])

dfs_to_keep = [] 
for group_name, group_df in group_dfs:
    if len(group_df) < TARGET_SAMPLES:
        logger.info(f"Generating {TARGET_SAMPLES-len(group_df)} samples for {group_name}")
        # generate samples
        model_name = group_df["model_name_or_path"].iloc[0]
        method = group_df["method"].iloc[0]
        dataset = group_df["dataset"].iloc[0]
        author_keys = group_df["author_key"].iloc[0]
        command = f"./run_iota.sh {model_name} {method} {dataset} {author_keys}"
        logger.info(command)
        # run command
        # os.system(command)

    if len(group_df) > TARGET_SAMPLES:
        logger.info(f"Removing {len(group_df)-TARGET_SAMPLES} ({len(group_df)} - {TARGET_SAMPLES}) samples for {group_name}")
        # keep only TARGET_SAMPLES amount of the samples with the latest date
        group_df = group_df.sort_values(by="date", ascending=False)
        group_df = group_df.head(TARGET_SAMPLES)
    
    dfs_to_keep.append(group_df)

# combine dfs and reset index 
df = pd.concat(dfs_to_keep, ignore_index=True)

# we should have # leaf nodes x 3 (test cases) x 5 (TARGET_SAMPLES) rows in the df
logger.info(f"Expected length: {len(leaf_dirs) * 3 * TARGET_SAMPLES}")

print(f"Ending length: {len(df)}")

# save to all_results.jsonl
df.to_json(out_dir / "all_results_compiled.jsonl", orient="records", lines=True)